name: SSH

on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
 test-ssh:
    runs-on: ubuntu-20.04
    steps:
      - name: SCP
        env:
          S390X_SSH_HOST: ${{ secrets.S390X_SSH_HOST }}
          S390X_SSH_KEY: ${{ secrets.S390X_SSH_KEY }}
          S390X_SSH_USER: ${{secrets.S390X_SSH_USER }}
        run: |
          mkdir ~/.ssh
          ls ~/
          chmod 700 ~/.ssh
          touch ~/.ssh/id_builder_s390x
          ls -l ~/.ssh/
          chmod 700 ~/.ssh/id_builder_s390x
          echo "$S390X_SSH_KEY" > ~/.ssh/id_builder_s390x
          ls -l ~/.ssh/
          ssh -i ~/.ssh/id_builder_s390x -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $S390X_SSH_USER@$S390X_SSH_HOST "ls -lart"
          scp -i ~/.ssh/id_builder_s390x -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r $S390X_SSH_USER@$S390X_SSH_HOST:/root/py-spy . 
          ls -lrt
